spring.application.name=event_booking

server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/event_booking_db
spring.data.mongodb.database=event_booking_db

jwt.secret=ThisIsMyVerySecretKeyForEventBookingSystem2026SpringBootJWT
jwt.expiration=86400000